### ISSUE TITLE
Talking about memory

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/mids_coursera#18]
@kylebradbury at some point, we should think about the level of detail we want to get into about how memory works. When writing about vectors, I've mostly said "they're like lists, but homogeneously typed", which begs the question "well... isn't that worse"? I can just say "no, don't worry -- it's worth it 'cause they're fast", but I'm wondering if we should dive into why. 

I started to write something on [that here](https://github.com/nickeubank/mids_coursera/blob/main/practicaldatascience_materials/40_wide_numpy_is_fast_memory_explanation.ipynb) (to be mid-week 2) before deciding it was out of place, and probably too much detail. We talk about this in part in the [week 4 vectorization reading](https://github.com/nickeubank/mids_coursera/blob/main/practicaldatascience_materials/40_wide_numpy_is_fast_memory_explanation.ipynb), but only indirectly. 

So at some point, we should think about how much detail about the concept of contiguous memory allocations is appropriate.

**Comment by kylebradbury** [comment]
It's an interesting question - this gets at the point around eliminating the magic. Do we know if Drew and Genevieve are discussing representation in memory? I think this would make a great "extra" that's not required for the interested student. I know we can have a few "optional" pieces, and I think that would be a good candidate for that designation since you can continue without that information, but it would be informative if students were scratching their heads around whether the speed difference is real.
