### ISSUE TITLE
Thousands _

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/mids_coursera#21]
Don't know if you've noticed, by python recently started allowing `_` in numbers to act as comma separators. I _love_ this feature! e.g. you can type:

`x = 1_000_000` instead of `x = 1000000`. 

Might I suggest we use that throughout?

**Comment by kylebradbury** [comment]
Sounds good to me - let's add a 1-liner at first use of this syntax to explain it (and that it's not common among other languages, so they don't try to use it in R or something). How about we create a "formatting checklist" of things we'll want to review for since we have a few now? I'll create an issue with that!
