### ISSUE TITLE
Week 3 Updates!

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/mids_coursera#23]
OK! Week three is super rough draft done I think. Wanna poke around in week 2 and week 3 and let me know what you think? 

Things I know need attention in Week 3:

- Views and Copies is gonna require a lot of figures to illustrate what's happening in memory. Will leave that to you / DLI / myself later. 
- I need to write up array broadcasting rules in `40_nd_arrays.ipynb`. Just... don't want want. I even more didn't want to draft views/copies, so I made myself do that first. :) 
- I think the example in `40_nd_arrays.ipynb` would be more interesting if I didn't just put random numbers into the 3-D array. I was also thinking about trying to get an MRI scan to use?

**Comment by nickeubank** [comment]
Added broadcasting rules.

**Comment by kylebradbury** [comment]
- I really like the approach - I think it's a clear explanation of views and copies (which is a very tricky subject to explain!). I would be happy to work on cleaning up the figures if it's useful - let's see what DLI's thoughts are on the section then I'd be happy to take the figures as an action item.
- For views and copies, do you think it would be interesting to show the performance difference between using a passed reference and making a copy? The one thing that comes to mind is whether the students would internalize the impact making a copy would have and they might be wondering what the value of views are.

A few other minor bits and bobs from these weeks (happy to work on some of these, if you agree with the suggestions and it would be helpful):
- 15: We may want some further discussion of ":" for indexing before this since this exercise uses it (or to bring the discussion of that up a bit)
- 15: Perhaps swap exercise 2 and 3 (starting with the form they've likely seen first)
- 20: would graphics help for folding and reshaping? Happy to draft one or two to get the idea across?
- 20: Could we use data in the plural rather than the singular?
- 35: Could we briefly introduce hstack?
- 40: would some visuals help for broadcasting? Happy to create a couple
- 45: May need a reminder of the function of the modulo operator

Great work on drafting these!

**Comment by nickeubank** [comment]
> For views and copies, do you think it would be interesting to show the performance difference between using a passed reference and making a copy? The one thing that comes to mind is whether the students would internalize the impact making a copy would have and they might be wondering what the value of views are.

That seems pretty advanced. I mean... I have *never* thought about performance implications when working with views and copies, and generally default to copies if I'm ever nervous because I care more about data integrity than speed 99.9% of my time, and don't trust myself with views. But happy to incorporate if you'd like.

**Comment by nickeubank** [comment]
> 15: We may want some further discussion of ":" for indexing before this since this exercise uses it (or to bring the discussion of that up a bit)

I went back to the vector subsetting (`week_2/30_subsetting_vectors.ipynb`) and talked more about it explicitly there. Also adding in `week_3/15`. But they should also have seen this with lists, no?

> 15: Perhaps swap exercise 2 and 3 (starting with the form they've likely seen first)

👍

> 20: would graphics help for folding and reshaping? Happy to draft one or two to get the idea across?

Sure!

> 20: Could we use data in the plural rather than the singular?

Yes! Sorry. Trying to be good about that. But um... where did I botch that? Not seeing, sorry. 

> 35: Could we briefly introduce hstack?

Done. 

> 40: would some visuals help for broadcasting? Happy to create a couple

Dear god yes. :) 

> 45: May need a reminder of the function of the modulo operator

Added.

**Comment by nickeubank** [comment]
> For views and copies, do you think it would be interesting to show the performance difference between using a passed reference and making a copy? The one thing that comes to mind is whether the students would internalize the impact making a copy would have and they might be wondering what the value of views are.

Went ahead and added a timed example and discussion of how much people should actually care!
