### ISSUE TITLE
People would be into my brain slices

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/mids_coursera#29]

**Comment by kylebradbury** [comment]
The name of this issue made me chuckle. Another 3D option to consider is remote sensing data. Easy with RGB data, but there are some hyperspectral datasets that may be interesting [such as this one](http://www.ehu.eus/ccwintco/index.php/Hyperspectral_Remote_Sensing_Scenes).

**Comment by nickeubank** [comment]
hmmmm yeah. Sounds like CCT may appreciate the medical application, but more than one example could definitely be fun.

What's 3D remote sensing? Would that be like lidar point clouds? Or do you mean 2-D spatial + dimension for different bands? We definitely want to touch on color images images as having three dimensions of data (I reference that in text, but an example would be great).

**Comment by kylebradbury** [comment]
2D spatial + dimension for different bands. Hyperspectral data is like RGB data, but with more channels. Typically we just have 3 bands (RGB), but those are just specific ranges of wavelengths (each one representing a range of color that we call red, green, or blue); hyper spectral imagery basically makes each of those bands narrower so you may have multiple types of "red" as well as some "colors" (used in quotes since not all are visible to the human eye) outside of the RGB range. The benefit of this is that different materials may have very specific responses in certain spectral bands, providing much more information about a given surface and its material composition.

Lidar point clouds are really interesting, although doesn't necessarily fit nicely into a 3D matrix form.

What would be even better would be something like a thermal 3D data cube so the dimensions are all spatial, although these are unlikely to be public. I have come across a few datasets of things like 3D volumetric models of objects, etc., can find a few examples on [this page](https://github.com/jianwen-xie/3DDescriptorNet).

As I'm writing this, perhaps a simple RGB example may be interesting and simple enough to explain, especially if it's of an area that student may be familiar with. For example - could look at RGB data of a capitol or natural "wonder" of the world... I could prepare one. Thoughts?

**Comment by nickeubank** [comment]
OK, realized my brain MRI was pre-duke (I just have lame stuff, like neck and spine. Pfff). [But this exists, so...](https://openfmri.org/dataset/)

**Comment by nickeubank** [comment]
No... moved here https://openneuro.org/
