### ISSUE TITLE
Code flow images

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/mids_coursera#31]
OK, here's the family of images that need updating:

https://github.com/nickeubank/mids_coursera/blob/main/class_2/week_2/30_subsetting_vectors.ipynb

and for week 3, view / copies are closely related:

https://github.com/nickeubank/mids_coursera/blob/main/class_2/week_3/10_views_and_copies.ipynb

**Comment by kylebradbury** [comment]
I've taken a stab at updating those - here's a [pdf of the updated versions](https://github.com/nickeubank/mids_coursera/blob/main/figure_prep/figures-views-and-copies.pdf) for reviewing. The ppt file is also there, but figured pdf was easier to review. I went through D&G's content and tried to follow their general convention (trying to keep the general aesthetic and logic in tact) and build on it to be able to clearly convey the operations we were trying to show in week 3. Let me know if I could iterate to make it clearer, and once we're happy with it, I can add more to highlight other operations that could benefit from similar illustration.

**Comment by nickeubank** [comment]
omg those are so good! I love them so much. Aside from still feeling a little bit queasy about seeing my "lie" about views and copies from the subsetting reading in a pretty picture (don't get me wrong I still think it's the right decision, just an instructional move I don't think I've ever used before), I think they're perfect.

**Comment by nickeubank** [comment]
Ping me when you feel good with them and I'll put into the actual materials?

**Comment by kylebradbury** [comment]
Glad you like them! I think they're good-to-go, too. I agree it makes sense at this point in the discussion to keep it straightforward with what's going with views/copies, especially since we address that later and dive into the next level of complexity. Happy to work on the images for the views/copies section to see what we can do to make that particularly clear. I made some individual images and added them to the figures folder for week 2. Let me know if there's a better way of sharing those, of course.

**Comment by nickeubank** [comment]
subsummed by #43
