### ISSUE TITLE
New image for image reading (not copyrighted!)

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/mids_coursera#51]

**Comment by kylebradbury** [comment]
In case it's helpful, all of these images are options for use, since I took them: https://pixabay.com/users/kylebradbury-7327150/

**Comment by nickeubank** [comment]
Last we were on this, I think @mvhudson-duke said he thought we should just run with fair use?

**Comment by nickeubank** [comment]
@mvhudson-duke Are we just going to try for fair use?

**Comment by mvhudson-duke** [comment]
Okay Sorry for the late response. I talked to the rest of my team and we had a nice solid debate about copyright issues, and the eventual consensus is that Monty Python isn't important enough to the direct educational use to have a particularly strong fair use argument. So their recommendations were, in order of desirability:

- find an open source image (preferably of a python to maintain the pun) to replace that image
- alter or adapt the image in question in some way so that it's not able to be considered a direct rip off
- use it as/is and hope we don't get called on it

**Comment by mvhudson-duke** [comment]
Additionally, one of my coworkers searched for some open source monty python images, and actually found some more. Her vote was for this one:

https://commons.wikimedia.org/wiki/File:Monty_Python_Live_02-07-14_12_29_21_(14415376859).jpg

**Comment by kylebradbury** [comment]
In that case, I'd vote for a random photo of some variety. The photo above is amusing, for sure, haha. An actual picture of a python snake could work ([like this one:](https://pixabay.com/photos/python-snake-reptile-animal-1866944/)). Any sense of whether that would be aversive to some? Otherwise, an amusing and appealing photo should do.

**Comment by nickeubank** [comment]
OK, in 2011 the Royal Mail issued this stamp:

![spamalot_stamp_color](https://user-images.githubusercontent.com/9683693/202030776-40a83df4-b409-47b8-9729-ff83490421cb.jpeg)

So I'm using a lowish quality version of that that I THINK is what was on royal mail site, but which I pulled from a stampcollectors forum.

**Comment by kylebradbury** [comment]
Just poked around copyright status of stamps in the UK (https://commons.wikimedia.org/wiki/Commons:Stamps#United_Kingdom): 

"British stamp designs published before 1st October 1969 were "Crown Copyright", which expired after 50 years and put the stamps in the public domain. (See [Crown copyright](https://en.wikipedia.org/wiki/en:Crown_copyright).) This also applies to the stamps of the various territories of the British Empire prior to their independence.

In 1969, the Post Office was established as a non-Crown body. Since then, **the copyright of new British stamps has been held by the Post Office or [Royal Mail](https://en.wikipedia.org/wiki/en:Royal_Mail)** in its own right, so in general no stamp may be uploaded."

**Comment by nickeubank** [comment]
WHAT?! BOOOO. OK, fine, will just pick something silly.
