### ISSUE TITLE
Course 3, week 3

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/mids_coursera#53]
OK, finally got file types and the view/copy shit show readings done. The file types was new, and the view/copy shitshow took some revisions because of changes to how pandas works. Sigh. But should have my stuff done for Course 3 by end of month as planned. As for course 5... see new issue.

**Comment by kylebradbury** [comment]
That's fantastic to hear - let me know when it would be helpful to start taking a look. Congrats on the view/copy stuff is really tough (all the more so because it's not always entirely consistent depending on the method that you're using). Really glad to hear this! I'm also on track for end-of-month delivery.

**Comment by nickeubank** [comment]
OK, think instructional content is good. Gotta work on exercises, but we're close!

**Comment by nickeubank** [comment]
Ok think week 3 is set!
