### ISSUE TITLE
finish week 4 color reading

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/mids_coursera#79]
How would you feel about moving the discussion of color images into the beginning of week 4? While playing with these I remembered the reason that I didn't introduce color images in the original reading is that "images as matrices" comes before we talk about higher dimensional arrays.

We could talk about color images and put in this JWST exercise at the end of Week 3, but I think it's getting really crowded there, and I think it might make a lot more sense to move it both to the front of week 4.

I put a draft of a color image reading here: https://github.com/nickeubank/mids_coursera/blob/main/class_2/week_4/00_color_images_as_arrays.ipynb

Needs a "second move" as it were, then we need to add JWST. 

Thoughts?

**Comment by nickeubank** [comment]
@sarwaridas

**Comment by kylebradbury** [comment]
I think that would fit well there - both the reading and the exercise. Mind if I build out the reading a bit more? Happy to insert it into the week as well (likely after summarization). I actually think this could be a great summarization exercise as well since a grayscale image is the average of pixel intensities along the channels. I'll assign myself this one.

**Comment by kylebradbury** [comment]
I've reordered this reading and expanded it a bit. Check it out when you have a chance and reopen if there are any other edits you'd like to suggest!

**Comment by nickeubank** [comment]
Looks perfect!
